### ISSUE TITLE
502 Error code by calling luftdaten.info

### ISSUE THREAD

**Issue by lluszczynski** [opendata-stuttgart/luftdaten.info#4]
I'm getting 502 HTTP status when I'm trying to access http://luftdaten.info/
See attachement.
![luftdaten_502](https://cloud.githubusercontent.com/assets/13704009/25798460/87f6c77a-33e1-11e7-9328-3fcca5bb156b.png)

**Comment by ricki-z** [comment]
As you see the page is TEMPORARILY unavailable. We are working on this.
